# Generated by Django 3.2 on 2021-04-29 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0012_auto_20210428_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('prenom', models.CharField(max_length=256)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=256, null=True)),
                ('grade', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Nouvelle', 'Nouvelle'), ('Redoublant', 'Redoublant'), ('Redoublante', 'Redoublante')], max_length=256, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='etablissements.classe')),
            ],
            options={
                'verbose_name': 'Elève',
                'verbose_name_plural': 'Elèves',
                'db_table': 'eleve',
            },
        ),
    ]
