# Generated by Django 3.2 on 2021-05-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='grade',
            new_name='statut',
        ),
    ]
