# Generated by Django 3.2 on 2021-04-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('type', models.CharField(blank=True, choices=[('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel')], max_length=256, null=True)),
                ('periode', models.CharField(max_length=256)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Découpage',
                'verbose_name_plural': 'Découpages',
                'db_table': 'decoupage',
            },
        ),
    ]
