# Generated by Django 3.2 on 2021-04-23 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0002_decoupage'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoupage',
            name='anneescolaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decoupages', to='etablissements.anneescolaire'),
        ),
    ]
