# Generated by Django 3.2 on 2021-04-23 20:08

from django.db import migrations, models
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0003_decoupage_anneescolaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('rep', models.CharField(blank=True, max_length=256, null=True)),
                ('adresse', models.CharField(max_length=256)),
                ('pays', django_countries.fields.CountryField(blank=True, help_text='Pays', max_length=2, null=True)),
                ('contact', phone_field.models.PhoneField(blank=True, help_text='Numéro de téléphone', max_length=31, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Direction Régionnale',
                'verbose_name_plural': 'Directions Régionnales',
                'db_table': 'dre',
            },
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='nom',
            field=models.CharField(max_length=11),
        ),
    ]
