# Generated by Django 3.2 on 2021-04-23 20:13

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0004_auto_20210423_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dre',
            name='contact',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
