# Generated by Django 3.2 on 2021-04-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0005_alter_dre_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dre',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
