# Generated by Django 3.2 on 2021-04-23 21:00

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0008_inspection_dre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('prenom', models.CharField(max_length=256)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=256)),
                ('grade', models.CharField(choices=[('PR', 'Professeur'), ('MCA', 'Maitre de conference A'), ('MCB', 'Maitre de conference B'), ('MAA', 'Maitre assistant A'), ('MAB', 'Maitre assistant B'), ('DR', 'Docteur'), ('M', 'Master'), ('M1', 'Master I'), ('L', 'Licence')], max_length=256)),
                ('nationalite', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=256, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'db_table': 'enseignant',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('dre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='etablissements.inspection')),
            ],
            options={
                'verbose_name': 'Etablissement',
                'verbose_name_plural': 'Etablissements',
                'db_table': 'etablissement',
            },
        ),
    ]
