# Generated by Django 3.2 on 2021-04-23 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0009_enseignant_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='etbs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='etablissements.etablissement'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='chef',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chefetb', to='etablissements.enseignant'),
        ),
    ]
