# Generated by Django 3.2 on 2021-04-28 19:23

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0010_auto_20210423_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('grade', models.CharField(choices=[('A4', 'A4'), ('S', 'S'), ('D', 'D'), ('C4', 'C'), ('E', 'E'), ('F2', 'F2'), ('F4', 'F4'), ('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3')], max_length=256)),
                ('nationalite', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=256, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etbs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='etablissements.etablissement')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'db_table': 'classe',
            },
        ),
    ]
