# Generated by Django 3.2 on 2021-04-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0011_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'db_table': 'matiere',
            },
        ),
        migrations.RenameField(
            model_name='classe',
            old_name='grade',
            new_name='serie',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='nationalite',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=256),
        ),
    ]
