# Generated by Django 3.2 on 2021-10-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0013_matiereclasse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneescolaire',
            options={},
        ),
        migrations.AlterModelTable(
            name='anneescolaire',
            table=None,
        ),
    ]
