# Generated by Django 3.2 on 2021-10-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0014_auto_20211013_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneescolaire',
            options={'verbose_name': 'Année scolaire', 'verbose_name_plural': 'Années scolaires'},
        ),
        migrations.AlterModelTable(
            name='anneescolaire',
            table='annee_scolaire',
        ),
    ]
