# Generated by Django 3.2 on 2021-10-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0015_auto_20211013_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneescolaire',
            options={},
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={},
        ),
        migrations.AlterModelOptions(
            name='decoupage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='etablissement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inspection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matiereclasse',
            options={},
        ),
        migrations.AlterModelTable(
            name='anneescolaire',
            table=None,
        ),
        migrations.AlterModelTable(
            name='classe',
            table=None,
        ),
        migrations.AlterModelTable(
            name='decoupage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dre',
            table=None,
        ),
        migrations.AlterModelTable(
            name='enseignant',
            table=None,
        ),
        migrations.AlterModelTable(
            name='etablissement',
            table=None,
        ),
        migrations.AlterModelTable(
            name='inspection',
            table=None,
        ),
        migrations.AlterModelTable(
            name='matiere',
            table=None,
        ),
        migrations.AlterModelTable(
            name='matiereclasse',
            table=None,
        ),
    ]
