# Generated by Django 3.2 on 2021-10-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0016_auto_20211013_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneescolaire',
            options={'verbose_name': 'Année scolaire', 'verbose_name_plural': 'Années scolaires'},
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='decoupage',
            options={'verbose_name': 'Découpage', 'verbose_name_plural': 'Découpages'},
        ),
        migrations.AlterModelOptions(
            name='dre',
            options={'verbose_name': 'Direction Régionnale', 'verbose_name_plural': 'Directions Régionnales'},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'verbose_name': 'Enseignant', 'verbose_name_plural': 'Enseignants'},
        ),
        migrations.AlterModelOptions(
            name='etablissement',
            options={'verbose_name': 'Etablissement', 'verbose_name_plural': 'Etablissements'},
        ),
        migrations.AlterModelOptions(
            name='inspection',
            options={'verbose_name': 'Inspection', 'verbose_name_plural': 'Inspections'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterModelOptions(
            name='matiereclasse',
            options={'verbose_name': 'Matière de la classe', 'verbose_name_plural': 'Matières de la classe'},
        ),
        migrations.AlterModelTable(
            name='anneescolaire',
            table='annee_scolaire',
        ),
        migrations.AlterModelTable(
            name='classe',
            table='classe',
        ),
        migrations.AlterModelTable(
            name='decoupage',
            table='decoupage',
        ),
        migrations.AlterModelTable(
            name='dre',
            table='dre',
        ),
        migrations.AlterModelTable(
            name='enseignant',
            table='enseignant',
        ),
        migrations.AlterModelTable(
            name='etablissement',
            table='etablissement',
        ),
        migrations.AlterModelTable(
            name='inspection',
            table='inspection',
        ),
        migrations.AlterModelTable(
            name='matiere',
            table='matiere',
        ),
        migrations.AlterModelTable(
            name='matiereclasse',
            table='matiere_classe',
        ),
    ]
