# Generated by Django 3.2 on 2021-10-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0018_auto_20211013_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='etbs',
        ),
    ]
